Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.95.5"
  config.vm.box = "ubuntu/bionic64"
  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y docker.io docker-compose
    sudo apt install gnupg2 pass -y
    systemctl enable docker
    systemctl start docker
    curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.8.1/kind-linux-amd64
    chmod +x ./kind
    mv ./kind /usr/local/bin
    kind create cluster
    snap install kubectl --classic
  SHELL
end
